/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.pms;

import org.junit.Test;

public class AppTest {
  @Test public void testAppHasAGreeting() {
    //        ClientApp classUnderTest = new ClientApp();
    //        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
  }
}
